[build]
target = "aarch64-unknown-none"

[target.aarch64-unknown-none]
linker = "rust-lld"
rustflags = [
    "-C", "link-arg=--build-id=none",
    "-C", "link-arg=-nostdlib",
    "-C", "relocation-model=static",
]

[unstable]
build-std = ["core", "alloc"]
build-std-features = ["compiler-builtins-mem"]