[package]
name = "plum_bootloader"
version = "0.1.0"
edition = "2021"

[dependencies]
uefi = { version = "0.35.0", features = ["alloc", "global_allocator", "panic_handler"] }
plam = { path = "crates/plam" }
