[package]
name = "plum-config"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.29"
crossterm = "0.29"
serde = { version = "1.0", features = ["derive"] }
toml = "0.9.8"
dialoguer = "0.12.0" 