[package]
name = "ppm-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
ppm-core = { path = "../../../../../sdk/lib/ppm-core", features = ["cli"] }
ratatui = "0.29.0"
crossterm = "0.29.0"
anyhow = "1.0.100"
tokio = { version = "1.48.0", features = ["full"] }